blogTitle: Magda and Antoine and the Van
baseURL: afauroux.github.io/MagdaAndAntoineAndTheVan
description: We are a recently engaged Franco-Polish couple travelling the world in a homemade van taking pictures along the way.